### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by saraswat** [mmessmer/glueSemWorkbench#7]
Also, any possibility that the source code could also be licensed under a commercial-friendly license, such as Apache / MIT / BSD / Eclipse?

We would be able to contribute (pull requests) if that were the case.

Thanks!

**Comment by saraswat** [comment]
Hello --any progress on this issue? Thanks!

**Comment by mmessmer** [comment]
Hi, sorry for the long response time. We changed the license to the Apache 2.0 license, so it should be more commercial-friendly now and we would love to have you and other people interested in glue semantics contribute to the project.
